
// This file was autogenerated by PeakRDL-uvm
package uvm_reg_model;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - regs_level_t_ext_hdl_path_4d34f533::control_reg
    class regs_level_t_ext_hdl_path_4d34f533__control_reg extends uvm_reg;
        rand uvm_reg_field en;
        rand uvm_reg_field mode;

        function new(string name = "regs_level_t_ext_hdl_path_4d34f533__control_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.en = new("en");
            this.en.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.mode = new("mode");
            this.mode.configure(this, 3, 1, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : regs_level_t_ext_hdl_path_4d34f533__control_reg

    // Reg - regs_level_t_ext_hdl_path_4d34f533::status_reg
    class regs_level_t_ext_hdl_path_4d34f533__status_reg extends uvm_reg;
        rand uvm_reg_field ready;
        rand uvm_reg_field error;

        function new(string name = "regs_level_t_ext_hdl_path_4d34f533__status_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ready = new("ready");
            this.ready.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.error = new("error");
            this.error.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : regs_level_t_ext_hdl_path_4d34f533__status_reg

    // Addrmap - regs_level_t_ext_hdl_path_4d34f533
    class regs_level_t_ext_hdl_path_4d34f533 extends uvm_reg_block;
        rand regs_level_t_ext_hdl_path_4d34f533__control_reg CTRL;
        rand regs_level_t_ext_hdl_path_4d34f533__status_reg STAT;

        function new(string name = "regs_level_t_ext_hdl_path_4d34f533");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.CTRL = new("CTRL");
            this.CTRL.configure(this);

            this.CTRL.build();
            this.default_map.add_reg(this.CTRL, 'h0);
            this.STAT = new("STAT");
            this.STAT.configure(this);
            STAT.add_hdl_path_slice("BLOCKSTAT", -1, -1);
            this.STAT.build();
            this.default_map.add_reg(this.STAT, 'h4);
        endfunction : build
    endclass : regs_level_t_ext_hdl_path_4d34f533

    // Addrmap - sub_b_t_ext_hdl_path_01af664b
    class sub_b_t_ext_hdl_path_01af664b extends uvm_reg_block;
        rand regs_level_t_ext_hdl_path_4d34f533 regs_inst;

        function new(string name = "sub_b_t_ext_hdl_path_01af664b");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.regs_inst = new("regs_inst");
            this.regs_inst.configure(this);
            this.regs_inst.build();
            this.default_map.add_submap(this.regs_inst.default_map, 'h0);
        endfunction : build
    endclass : sub_b_t_ext_hdl_path_01af664b

    // Addrmap - sub_a_t_ext_hdl_path_b28354b5
    class sub_a_t_ext_hdl_path_b28354b5 extends uvm_reg_block;
        rand sub_b_t_ext_hdl_path_01af664b sub_b_inst;

        function new(string name = "sub_a_t_ext_hdl_path_b28354b5");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.sub_b_inst = new("sub_b_inst");
            this.sub_b_inst.configure(this);
            this.sub_b_inst.build();
            this.default_map.add_submap(this.sub_b_inst.default_map, 'h100);
        endfunction : build
    endclass : sub_a_t_ext_hdl_path_b28354b5

    // Addrmap - top_t
    class top_t extends uvm_reg_block;
        rand sub_a_t_ext_hdl_path_b28354b5 sub_a_inst;

        function new(string name = "top_t");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.sub_a_inst = new("sub_a_inst");
            this.sub_a_inst.configure(this);
            this.sub_a_inst.build();
            this.default_map.add_submap(this.sub_a_inst.default_map, 'h1000);
        endfunction : build
    endclass : top_t

endpackage: uvm_reg_model
status_reg.add_hdl_path_slice("tb_top.top.sub_a.BLOCK.STAT", -1, -1)
CTRL.add_hdl_path_slice("tb_top.top.sub_a.BLOCK.STAT", -1, -1)
